apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: lab-container-training
spec:
  portal:
    registration:
      type: anonymous
    password: happy-birthday-paul
    capacity: 100
    # capacity: 10
    # reserved: 60
    initial: 60
    # initial: 4
    # expires: 8h
    # orphaned: 15m
    ingress:
      hostname: "learn"
  workshops:
  - name: lab-container-training
